# fly.toml app configuration file generated for cms-platform on 2026-09-21T22:07:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cms-platform'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = '/bin/sh -c "php artisan migrate --force && php artisan tenants:migrate --force"'

[env]
  APP_ENV = 'production'
  CACHE_STORE = 'redis'
  DB_CONNECTION = 'pgsql'
  FILESYSTEM_DISK = 'public'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'error'
  NUXT_API_BASE_SSR = 'http://127.0.0.1:8080/api/v1'
  QUEUE_CONNECTION = 'redis'
  SESSION_DRIVER = 'redis'

[[mounts]]
  source = 'webnova_storage'
  destination = '/var/www/html/storage'
  initial_size = '5gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '10s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/up'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
